# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\PedestrianDetectionCodes\PyQt\CSP_Det\track_test.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *
from PyQt5.QtGui import *
from PyQt5.QtCore import *


class MySlider(QSlider):  # 继承QSlider
    customSliderClicked = pyqtSignal(str)  # 创建信号

    def __init__(self, parent=None):
        super(QSlider, self).__init__(parent)

    def mousePressEvent(self, QMouseEvent):  # 重写的鼠标点击事件
        super().mousePressEvent(QMouseEvent)
        pos = QMouseEvent.pos().x() / self.width()
        self.setValue(round(pos * (self.maximum() - self.minimum()) + self.minimum()))  # 设定滑动条滑块位置为鼠标点击处
        self.customSliderClicked.emit("mouse Press")  # 发送信号

class Ui_TrackTestWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("识别与跟踪")
        MainWindow.resize(1350, 900)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.toolButton_2 = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_2.setGeometry(QtCore.QRect(20, 10, 150, 60))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.toolButton_2.setFont(font)
        self.toolButton_2.setObjectName("toolButton_2")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(110, 390, 101, 41))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.toolButton_6 = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_6.setGeometry(QtCore.QRect(70, 540, 140, 60))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.toolButton_6.setFont(font)
        self.toolButton_6.setObjectName("toolButton_6")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(240, 150, 1080, 720))
        self.label_2.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_2.setScaledContents(True)
        self.toolButton_5 = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_5.setGeometry(QtCore.QRect(20, 80, 150, 60))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.toolButton_5.setFont(font)
        self.toolButton_5.setObjectName("toolButton_5")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 390, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_4.setObjectName("label_4")
        self.toolButton_7 = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_7.setGeometry(QtCore.QRect(1230, 10, 101, 51))
        self.toolButton_7.setObjectName("toolButton_7")
        self.toolButton_8 = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_8.setGeometry(QtCore.QRect(70, 460, 140, 60))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.toolButton_8.setFont(font)
        self.toolButton_8.setObjectName("toolButton_8")
        self.toolButton_9 = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_9.setGeometry(QtCore.QRect(300, 90, 130, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.toolButton_9.setFont(font)
        self.toolButton_9.setObjectName("toolButton_9")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(430, 90, 200, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.toolButton_10 = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_10.setGeometry(QtCore.QRect(720, 80, 140, 60))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.toolButton_10.setFont(font)
        self.toolButton_10.setObjectName("toolButton_10")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1350, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.slider = MySlider(self.centralwidget)#水平方向
        self.slider.setGeometry(QtCore.QRect(440, 20, 280, 50))
        self.slider.setOrientation(QtCore.Qt.Horizontal)
        self.slider.setMinimum(0)#设置最小值
        self.slider.setMaximum(100)#设置最大值
        self.slider.setSingleStep(1)#设置步长值
        self.slider.setValue(50)#设置当前值
        self.slider.setTickPosition(QSlider.TicksRight)#设置刻度位置，在下方
        self.slider.setTickInterval(10)#设置刻度间隔
        self.slider.valueChanged.connect(self.changeVal)

        self.slider_2 = MySlider(self.centralwidget)#水平方向
        self.slider_2.setGeometry(QtCore.QRect(920, 20, 280, 50))
        self.slider_2.setOrientation(QtCore.Qt.Horizontal)
        self.slider_2.setMinimum(0)#设置最小值
        self.slider_2.setMaximum(100)#设置最大值
        self.slider_2.setSingleStep(1)#设置步长值
        self.slider_2.setValue(50)#设置当前值
        self.slider_2.setTickPosition(QSlider.TicksRight)#设置刻度位置，在下方
        self.slider_2.setTickInterval(10)#设置刻度间隔
        self.slider_2.valueChanged.connect(self.changeVal)

        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(280, 30, 150, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_4")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(760, 30, 150, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_5")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1680, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "多目标识别与跟踪"))
        self.toolButton_2.setText(_translate("MainWindow", "视频跟踪"))
        self.comboBox.setItemText(0, _translate("MainWindow", "KCF"))
        self.comboBox.setItemText(1, _translate("MainWindow", "MIL"))
        self.comboBox.setItemText(2, _translate("MainWindow", "TLD"))
        self.comboBox.setItemText(3, _translate("MainWindow", "MEDIANFLOW"))
        self.comboBox.setItemText(4, _translate("MainWindow", "MOSSE"))
        self.comboBox.setItemText(5, _translate("MainWindow", "CSRT"))
        self.toolButton_6.setText(_translate("MainWindow", "结束"))
        self.toolButton_5.setText(_translate("MainWindow", "摄像头跟踪"))
        self.label_4.setText(_translate("MainWindow", "跟踪算法："))
        self.toolButton_7.setText(_translate("MainWindow", "返回主菜单"))
        self.toolButton_8.setText(_translate("MainWindow", "开始跟踪"))
        self.label_5.setText(_translate("MainWindow", "得分阈值：50"))
        self.label_7.setText(_translate("MainWindow", "NMS阈值：50"))
        self.toolButton_9.setText(_translate("MainWindow", "选择识别模型："))
        self.label_6.setText(_translate("MainWindow", "epoch_35.pth.tea"))
        self.toolButton_10.setText(_translate("MainWindow", "识别第一帧"))

    def changeVal(self, value):
        sender = self.sender()
        if sender == self.slider:
            self.slider.setValue(value)
            self.label_5.setText('得分阈值：' + str(value))
        elif sender == self.slider_2:
            self.slider_2.setValue(value)
            self.label_7.setText('NMS阈值：' + str(value))
